from __future__ import annotations

import asyncio
import logging
from typing import Any

import httpx

from app.claude_coder import ClaudeCoder, ClaudeCoderError
from app.config import get_settings
from app.git_ops import GitOps

logger = logging.getLogger(__name__)


class Worker:
    def __init__(self) -> None:
        settings = get_settings()
        self.backend_client = httpx.AsyncClient(
            base_url=settings.backend_url.rstrip("/"),
            timeout=30.0,
        )
        github_headers = {
            "Accept": "application/vnd.github+json",
            "X-GitHub-Api-Version": "2022-11-28",
        }
        if settings.github_token:
            github_headers["Authorization"] = f"Bearer {settings.github_token}"

        self.github_client = httpx.AsyncClient(
            base_url="https://api.github.com",
            headers=github_headers,
            timeout=30.0,
        )
        self.git_ops = GitOps()
        self.coder = ClaudeCoder()

    async def poll_tasks(self) -> list[dict[str, Any]]:
        response = await self.backend_client.get("/api/tasks/pending")
        response.raise_for_status()
        payload = response.json()
        return payload if isinstance(payload, list) else []

    async def process_task(self, task: dict[str, Any]) -> None:
        project_id = int(task["project_id"])
        github_owner = str(task["github_owner"])
        github_repo = str(task["github_repo"])
        issue_number = int(task["github_issue_number"])
        title = str(task.get("title") or f"Issue #{issue_number}")
        branch_name = f"feat/issue-{issue_number}"

        logger.info(
            "Processing project_id=%s repo=%s/%s issue=%s",
            project_id,
            github_owner,
            github_repo,
            issue_number,
        )

        repo_path = await asyncio.to_thread(self.git_ops.clone_or_pull, github_owner, github_repo)
        try:
            issue = await self._get_issue(github_owner, github_repo, issue_number)
            base_branch = await asyncio.to_thread(self.git_ops.create_branch, repo_path, branch_name)

            async def push_milestone(message: str) -> None:
                await self._post_progress(project_id, message)

            issue_body = issue.get("body") or ""
            prompt = (
                f"You are working in a freshly checked-out git branch `{branch_name}`. "
                f"Implement the following GitHub issue end-to-end. Read the existing repo "
                f"to understand conventions, write production-quality code, and (if a test "
                f"runner is configured) make sure tests pass. Do NOT run git commands — "
                f"the wrapping worker will commit and push for you.\n\n"
                f"--- Issue #{issue_number}: {title} ---\n{issue_body}"
            )

            run_result = await self.coder.develop(
                prompt=prompt,
                repo_path=repo_path,
                on_milestone=push_milestone,
            )

            commit_message = f"feat: implement issue #{issue_number}\n\nGenerated by Claude Code via SuperUserAI Dev Agent."
            pushed = await asyncio.to_thread(
                self.git_ops.add_commit_push,
                repo_path,
                commit_message,
                branch_name,
            )
            if not pushed:
                raise RuntimeError(
                    "Claude Code finished but produced no file changes — nothing to commit."
                )

            pull_request = await self._create_pull_request(
                github_owner=github_owner,
                github_repo=github_repo,
                title=title,
                issue_number=issue_number,
                head_branch=branch_name,
                base_branch=base_branch,
                run_summary=run_result.summary,
            )
            await push_milestone(
                f"✅ 已提交 PR #{pull_request['number']}：{pull_request['html_url']}"
            )
            await self._notify_backend_completed(
                project_id,
                int(pull_request["number"]),
                branch=branch_name,
                summary=run_result.summary,
            )
        finally:
            try:
                await asyncio.to_thread(self.git_ops.checkout_main, repo_path)
            except Exception:
                logger.exception("Failed to restore default branch for %s", repo_path)

    async def run(self, interval: int = 30) -> None:
        try:
            while True:
                try:
                    tasks = await self.poll_tasks()
                    if tasks:
                        logger.info("Fetched %s pending task(s)", len(tasks))
                    for task in tasks:
                        try:
                            await self.process_task(task)
                        except Exception as exc:
                            logger.exception("Failed to process task: %s", task)
                            project_id = task.get("project_id")
                            if isinstance(project_id, int):
                                await self._notify_backend_failed(project_id, str(exc))
                except Exception:
                    logger.exception("Failed to poll pending tasks")

                await asyncio.sleep(interval)
        finally:
            await self.aclose()

    async def aclose(self) -> None:
        await self.backend_client.aclose()
        await self.github_client.aclose()

    async def _get_issue(self, github_owner: str, github_repo: str, issue_number: int) -> dict[str, Any]:
        response = await self.github_client.get(f"/repos/{github_owner}/{github_repo}/issues/{issue_number}")
        response.raise_for_status()
        data = response.json()
        return data if isinstance(data, dict) else {}

    async def _create_pull_request(
        self,
        github_owner: str,
        github_repo: str,
        title: str,
        issue_number: int,
        head_branch: str,
        base_branch: str,
        run_summary: str = "",
    ) -> dict[str, Any]:
        body_parts = [f"Closes #{issue_number}"]
        if run_summary.strip():
            body_parts.append("\n---\n## Claude Code Summary\n\n" + run_summary.strip())
        response = await self.github_client.post(
            f"/repos/{github_owner}/{github_repo}/pulls",
            json={
                "title": title,
                "body": "\n".join(body_parts),
                "head": head_branch,
                "base": base_branch,
            },
        )
        response.raise_for_status()
        data = response.json()
        if not isinstance(data, dict):
            raise ValueError("GitHub create PR response is not a JSON object")
        return data

    async def _notify_backend_completed(
        self,
        project_id: int,
        pr_number: int,
        *,
        branch: str | None = None,
        summary: str | None = None,
    ) -> None:
        payload: dict[str, Any] = {"pr_number": pr_number}
        if branch:
            payload["branch"] = branch
        if summary:
            payload["summary"] = summary
        response = await self.backend_client.post(
            f"/api/tasks/{project_id}/completed",
            json=payload,
        )
        response.raise_for_status()

    async def _notify_backend_failed(self, project_id: int, reason: str) -> None:
        try:
            response = await self.backend_client.post(
                f"/api/tasks/{project_id}/failed",
                json={"reason": reason[:4000]},
            )
            response.raise_for_status()
        except Exception:
            logger.warning(
                "Failed to notify backend about task failure project_id=%s",
                project_id,
                exc_info=True,
            )

    async def _post_progress(self, project_id: int, message: str) -> None:
        try:
            response = await self.backend_client.post(
                f"/api/projects/{project_id}/notify",
                json={"message": message},
            )
            response.raise_for_status()
        except Exception:
            logger.warning("Failed to push progress to backend: %s", message, exc_info=True)
